// SPDX-License-Identifier: AGPL-3.0-or-later
// Adapted from Misfit-Sanctuary/nuclear-14 @ <source-commit> (AGPL-3.0). See CONTRIBUTING.md §5.
using Content.Client._Zona14.WorldMap.Controls;
using Content.Shared._Zona14.WorldMap;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Zona14.WorldMap.Pda;

/// <summary>
/// The map widget: title, viewer control and annotation toolbar. Annotation edits are raised as
/// events; the host (PDA cartridge or standalone window) forwards them to the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WorldMapPdaUiFragment : BoxContainer
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    public event Action<WorldMapAnnotation>? OnAddAnnotation;
    public event Action<int>? OnRemoveAnnotation;
    public event Action? OnClearAnnotations;

    private readonly MapViewerControl _mapViewer;

    public WorldMapPdaUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _mapViewer = new MapViewerControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _mapViewer.OnAddAnnotation += annotation => OnAddAnnotation?.Invoke(annotation);
        _mapViewer.OnRemoveAnnotation += index => OnRemoveAnnotation?.Invoke(index);
        _mapViewer.OnClearAnnotations += () => OnClearAnnotations?.Invoke();
        MapContainer.AddChild(_mapViewer);

        PanModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.None);
            FooterText.Text = "Scroll to zoom | Click and drag to pan | Right click an annotation to delete it";
        };

        MarkerModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Marker);
            FooterText.Text = "Marker mode: left click to place a labeled marker";
        };

        BoxModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Box);
            FooterText.Text = "Box mode: drag to draw a labeled box";
        };

        DrawModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Draw);
            FooterText.Text = "Draw mode: click and drag to draw";
        };

        EraseButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Erase);
            FooterText.Text = "Erase mode: left or right click an annotation to remove it";
        };

        ClearMapButton.OnPressed += _ => _mapViewer.ClearAnnotations();
        AnnotationText.OnTextChanged += args => _mapViewer.SetPendingAnnotationText(args.Text);
        _mapViewer.SetPendingAnnotationText(AnnotationText.Text);

        BuildColorAndWidthControls();
        UpdateAnnotations(Array.Empty<WorldMapAnnotation>());
    }

    public void SetMap(string title, ResPath texturePath, Box2 worldBounds)
    {
        MapTitleLabel.Text = title;

        var fullPath = new ResPath("/Textures") / texturePath;
        if (!_resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
        {
            FooterText.Text = $"Missing map texture: {fullPath}";
            return;
        }

        _mapViewer.SetTexture(textureResource.Texture, worldBounds);
        _mapViewer.SetTrackedBlips(Array.Empty<MapTrackedBlip>());
    }

    public void UpdateAnnotations(WorldMapAnnotation[] annotations)
    {
        _mapViewer.SetAnnotations(annotations);
    }

    private void BuildColorAndWidthControls()
    {
        ColorRow.AddChild(new Label { Text = "Color: " });

        var swatchColors = new[]
        {
            new Color(0.95f, 0.50f, 0.15f, 1f),
            new Color(0.87f, 0.15f, 0.15f, 1f),
            new Color(0.94f, 0.88f, 0.10f, 1f),
            new Color(0.20f, 0.80f, 0.25f, 1f),
            new Color(0.20f, 0.60f, 1.00f, 1f),
            new Color(1.00f, 1.00f, 1.00f, 1f),
        };

        var swatchNames = new[]
        {
            "Orange",
            "Red",
            "Yellow",
            "Green",
            "Blue",
            "White",
        };

        for (var i = 0; i < swatchColors.Length; i++)
        {
            var captured = swatchColors[i];
            var button = new Button { Text = "■", ToolTip = swatchNames[i] };
            button.ModulateSelfOverride = captured;
            button.OnPressed += _ => _mapViewer.SetAnnotationColor(captured);
            ColorRow.AddChild(button);
        }

        ColorRow.AddChild(new Label { Text = " Width: " });

        var widths = new[] { 2f, 4f, 8f, 12f };
        var widthLabels = new[] { "Thin", "Med", "Thick", "Max" };

        for (var i = 0; i < widths.Length; i++)
        {
            var width = widths[i];
            var button = new Button { Text = widthLabels[i] };
            button.OnPressed += _ => _mapViewer.SetAnnotationStrokeWidth(width);
            ColorRow.AddChild(button);
        }
    }
}
