// SPDX-License-Identifier: AGPL-3.0-or-later
// Adapted from Misfit-Sanctuary/nuclear-14 @ <source-commit> (AGPL-3.0). See CONTRIBUTING.md §5.
using Content.Client.UserInterface.Controls;
using Content.Client._Zona14.WorldMap.Controls;
using Content.Shared._Zona14.WorldMap;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Zona14.WorldMap.Standalone;

[GenerateTypedNameReferences]
public sealed partial class WorldMapWindow : FancyWindow
{
    public event Action<WorldMapAnnotation>? OnAddAnnotation;
    public event Action<int>? OnRemoveAnnotation;
    public event Action? OnClearAnnotations;

    private readonly MapViewerControl _mapViewer;
    private ResPath? _loadedTexturePath;
    private Box2 _loadedBounds;
    private bool _hasLoadedMap;

    public WorldMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _mapViewer = new MapViewerControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _mapViewer.OnAddAnnotation += annotation => OnAddAnnotation?.Invoke(annotation);
        _mapViewer.OnRemoveAnnotation += index => OnRemoveAnnotation?.Invoke(index);
        _mapViewer.OnClearAnnotations += () => OnClearAnnotations?.Invoke();
        MapContainer.AddChild(_mapViewer);

        PanModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.None);
            FooterText.Text = "Scroll to zoom | Click and drag to pan | Right click an annotation to delete it";
        };

        MarkerModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Marker);
            FooterText.Text = "Marker mode: left click on the map to place a labeled marker";
        };

        BoxModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Box);
            FooterText.Text = "Box mode: drag on the map to draw a labeled box";
        };

        DrawModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Draw);
            FooterText.Text = "Draw mode: click and drag to freehand draw";
        };

        EraseButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Erase);
            FooterText.Text = "Erase mode: hover over an annotation and left click to delete it";
        };

        ClearMapButton.OnPressed += _ => _mapViewer.ClearAnnotations();
        AnnotationText.OnTextChanged += args => _mapViewer.SetPendingAnnotationText(args.Text);
        _mapViewer.SetPendingAnnotationText(AnnotationText.Text);

        ColorRow.AddChild(new Label { Text = "Color: " });

        var swatchColors = new[]
        {
            new Color(0.95f, 0.50f, 0.15f, 1f),
            new Color(0.87f, 0.15f, 0.15f, 1f),
            new Color(0.94f, 0.88f, 0.10f, 1f),
            new Color(0.20f, 0.80f, 0.25f, 1f),
            new Color(0.20f, 0.60f, 1.00f, 1f),
            new Color(1.00f, 1.00f, 1.00f, 1f),
        };

        var swatchNames = new[]
        {
            "Orange",
            "Red",
            "Yellow",
            "Green",
            "Blue",
            "White",
        };

        for (var i = 0; i < swatchColors.Length; i++)
        {
            var captured = swatchColors[i];
            var button = new Button { Text = "■", ToolTip = swatchNames[i] };
            button.ModulateSelfOverride = captured;
            button.OnPressed += _ => _mapViewer.SetAnnotationColor(captured);
            ColorRow.AddChild(button);
        }

        ColorRow.AddChild(new Label { Text = " Width: " });

        var widths = new[] { 2f, 4f, 8f, 12f };
        var widthLabels = new[] { "Thin", "Med", "Thick", "Max" };

        for (var i = 0; i < widths.Length; i++)
        {
            var width = widths[i];
            var button = new Button { Text = widthLabels[i] };
            button.OnPressed += _ => _mapViewer.SetAnnotationStrokeWidth(width);
            ColorRow.AddChild(button);
        }
    }

    public void SetMap(
        string title,
        ResPath texturePath,
        Box2 worldBounds,
        MapTrackedBlip[] trackedBlips,
        WorldMapAnnotation[] sharedAnnotations,
        bool compactHud)
    {
        MapTitle.Text = title;
        Title = title;
        ToolbarContainer.Visible = !compactHud;
        FooterContainer.Visible = true;

        if (!_hasLoadedMap || _loadedTexturePath != texturePath || _loadedBounds != worldBounds)
        {
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            var fullPath = new ResPath("/Textures") / texturePath;

            if (resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
            {
                _mapViewer.SetTexture(textureResource.Texture, worldBounds);
                _loadedTexturePath = texturePath;
                _loadedBounds = worldBounds;
                _hasLoadedMap = true;
            }
        }

        _mapViewer.SetTrackedBlips(trackedBlips);
        _mapViewer.SetAnnotations(sharedAnnotations);
    }
}
